version: "3.9"

services:
  db:
    image: postgres:16
    container_name: chakri_bakri_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chakri
      POSTGRES_PASSWORD: chakri_pass
      POSTGRES_DB: chakri_bakri
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: